databases:
  - name: task-manager
    plan: free
    databaseName: task_manager_db
    user: tulolo287

services:
  - type: web
    plan: free
    name: task-manager
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn task-manager.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task_manager_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4