name: Django test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: 3.12
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          python -m venv myenv
          source myenv/bin/activate
          pip install django
          make install
      - name: Make migrations
        run: |
          make migrate
      - name: Run Tests
        env:
          SECRET_KEY: ${{ secrets.DJANGO_SECRET }}
          DATABASE_URL: 'sqlite:///db.sqlite3'
          DEBUG: False
        run: |
          make test